=== nostromo97/fullXML/libros.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="libros">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="libro"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="libro">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="titulo"/>
                <xs:element ref="año"/>
                <xs:element ref="precio"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="titulo">
        <xs:complexType mixed="true">
            <xs:attribute name="lang" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="año" type="xs:integer"/>
    <xs:element name="precio">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:decimal">
                    <xs:attribute name="moneda"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nostromo97/fullXML/libros.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="libros.xsl"?>
<?xml-stylesheet href="libros.css"?>
<libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/carol/Desktop/fullXML/libros.xsd">
	<libro>
		<titulo>Everyday Italian</titulo>
		<año>• Año: 2005</año>
		<precio moneda="€">• 39.99</precio>
	</libro>
	<libro>
		<titulo>Harry Potter</titulo>
		<año>• Año: 2005</año>
		<precio moneda= "€">• 29.99</precio>
	</libro>
	<libro>
		<titulo>XQuery Kick Start</titulo>
		<año>• Año: 2003</año>
		<precio moneda= "€">• 49.99</precio>
	</libro>
	<libro>
		<titulo lang="en">Learning XML</titulo>
		<año>• Año: 2003</año>
		<precio>• 39.95</precio>
	</libro>
</libros>
